In [1]:
my_list = [1,2,3,4]
my_list


[1, 2, 3, 4]

In [4]:
import numpy as np
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3, 4])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
arr1 = np.array(my_mat)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [16]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
np.random.rand(5,5) 

array([[0.36095614, 0.82368325, 0.43298344, 0.3563326 , 0.10432617],
       [0.36792295, 0.02349991, 0.46206888, 0.264954  , 0.77812731],
       [0.47351515, 0.28546852, 0.17565242, 0.95335822, 0.79099149],
       [0.50061833, 0.01459773, 0.45734609, 0.67829386, 0.73708237],
       [0.61486473, 0.03977766, 0.15872075, 0.66198073, 0.63745553]])

In [19]:
np.random.randn(5)

array([ 0.00205838,  0.3123165 ,  1.65273672, -1.00824669,  0.40325524])

In [21]:
np.random.randint(1,100,10)

array([61, 23, 86, 56, 59, 25, 55, 77, 85, 12])

In [22]:
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ranarr = np.random.randint(1,100,10)

In [27]:
ranarr.max()

91

In [30]:
ranarr.min()

4

In [31]:
ranarr.argmax()

3

In [32]:
ranarr.argmin()

8

In [33]:
ranarr

array([57, 63, 79, 91, 61, 37, 64, 10,  4, 37])

In [34]:
arr.dtype

dtype('int32')

In [35]:
arr.shape

(25,)

In [36]:
arr = arr.reshape(5,5)

In [37]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr.shape

(5, 5)